### ISSUE TITLE
Adopting the ownership memory model

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#10]
We've been discussing if we should adopt the ownership memory model, of course the model alone would be very restrictive so we would probably have to implement borrowing. However, this model would simplify a number of concepts employed in the language.

**Comment by vnev** [comment]
I like this, despite the fact that we might get shit for ripping off Rust's model. We can probably say that we like what Rust did and think its a good way to program (which is true), but yeah we should do this

**Comment by raoulvdberge** [comment]
:-1:

**Comment by felixangell** [comment]
Changed my mind, let's not do this.

**Comment by MovingtoMars** [comment]
@felixangell Explanation? We should leave it on the table just in case.

**Comment by felixangell** [comment]
@MovingtoMars
I feel that it deviates from Ark's original goals of simplicity:

* the developer has to think more about how they're handling memory, which isn't necessarily a bad thing -- it just adds a huge mental burden on the programmer. 
* It's a very different way of programming, so people coming from a C, Ruby, ___ background will have a harder time learning to write Ark.
* It makes a lot of data structures and commonly used programming patterns pretty difficult (or non-trivial) to do, for instance a doubly linked list, or a cyclic graph.
* it's easier said than done, I imagine it will be very tricky to implement properly. We could learn from other languages that employ the feature (Rust), but then we would just be making a shitty rust clone
* Speaking of Rust, people will (probably) always compare Ark to Rust [if we employ this concept], I imagine people will probably ask why we don't do X how Rust does it, and that if we have this feature; we may as well add feature Y
* Most of the core team disagree with integrating ownership with Ark (while I agree with it to some extent, which is unfortunate)
* `unsafe` code, we'll have to support this too to break the rules of ownership (mostly for C interoperability)

However, this doesn't mean we wont do it. I do like the idea, yet I feel that it's not a great idea unless we think of a different way to do it so that:

* it's not a pain in the ass to write (i.e. it doesn't require loads of thought)
* it's not the exact same as Rust (so we aren't making Rusts goofy little brother)
* and probably a few other things?

**Comment by felixangell** [comment]
Actually, we decided to approve this...
