### ISSUE TITLE
Operator Overloading

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#11]
Specification for operator overloading:

**Comment by kiljacken** [comment]
Draft of spec for operator overloading: https://gist.github.com/kiljacken/8a8963cc176ada88c420

**Comment by MovingtoMars** [comment]
Why not use the symbols?

```
operator +(a Matrix, b Matrix) {
    
}
```

**Comment by felixangell** [comment]
I would prefer we had traits such as Add, Sub, etc. for specifying operator overloads.

**Comment by MovingtoMars** [comment]
@felixangell This allows symmetry.

**Comment by felixangell** [comment]
@MovingtoMars Explain? I've never been a heavy user of operator overloads.

**Comment by MovingtoMars** [comment]
It means that `matrix * 2` and `2 * matrix` can be done, and the results are guaranteed the same.

**Comment by kiljacken** [comment]
I've tweaked the draft according to your feedback @MovingtoMars. @felixangell another issue with reusing trats is that we would pollute the function namespace unnessecarily.

**Comment by MovingtoMars** [comment]
@kiljacken This looks quite nice now. I'm happy to see this implemented.

**Comment by felixangell** [comment]
Likewise, I'm going to close this and make an implementation issue on the compilers repo that references this.

**Comment by velkyel** [comment]
implicit symetry is bad. not all operations you want are comutative! At least there should be a choice what do you want to define or define both cases.

**Comment by kiljacken** [comment]
@velkyel That's exactly what's being proposed in my draft...

**Comment by velkyel** [comment]
@kiljacken I know, but this:

@MovingtoMars It means that matrix * 2 and 2 * matrix can be done, and the results are guaranteed the same.

means somenthing else I think. just for sure. Anyway ark is promissing and less syntax is less problems to solve in general at start.

**Comment by SamTebbs33** [comment]
@velkyel You use the `[ordered]` attribute to specify if the operands must come in a certain order.
