### ISSUE TITLE
char in C module

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#13]
I think it might be nice to have `char` in the `C` psuedo-module, which is basically a `u8`. While it is a bit redundant since it means the same thing, developers (especially new programmers) are more familiar with using `char` rather than specifying `u8`.

**Comment by kiljacken** [comment]
We might aswell go ahead and do mappings of all the C types as this rate lol.

**Comment by felixangell** [comment]
Fair point ;)
