### ISSUE TITLE
Implicit or Explicit interfaces?

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#15]
Traits were removed, which one should we pick? Give reasons for and against each of them, try be as neutral as possible in your arguments for and against.

@ark-lang/owners

**Comment by kiljacken** [comment]
:+1: for implicit. I feel like it's generally less of a hassle, compared to the additional syntax added by explicit interfaces.

**Comment by MovingtoMars** [comment]
+1 implicit

**Comment by MovingtoMars** [comment]
(accidentally closed)

**Comment by raoulvdberge** [comment]
I'm neutral about this. Implicit seems nice, but I wouldn't mind explicit as well.

**Comment by felixangell** [comment]
Looks like most of us are pretty set on implicit interfaces then.
