### ISSUE TITLE
Array syntax

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#16]
Instead of the syntax being `[]T`, I propose it should be `[T]`, with an optional length in the block: `[T; L]`, where `T` is the type, and `L` is the length.

Even if we don't adopt the `T` being placed in the block, as opposed to being on the right side of the block; it would be nice to adopt the semi-colon syntax for the array **initialiser**. I feel the syntax is nice, because it's similar to the idea of an array, e.g. an array consists of a type. An array can be considered a block of memory, the syntax represents the `T` inside of a block (of memory). 

```rust
// length is inferred
x: [int] = [0, 1, 2, 3, 4];

// length in type is superfluous in this case, 
// but the compiler should enforce that it 
// matches the length of the initialiser
x: [int; 5] = [0, 1, 2, 3, 4];

// array with the length 32, random data
// not zeroed out
x: [int; 32];

// shorthand for doing 32 `0`'s in an array initialiser
// again the length in the type here is superfluous
x: [int; 32] = [0; 32];

// slice of the previous `x` array
// note that the .. is exclusive
y: &[int] = &x[1..4];
```

**Comment by raoulvdberge** [comment]
I like `x: [int]` but honestly, `[int; 5]` seems uglier then `[5]int`.

**Comment by kiljacken** [comment]
Gonna dupe this here:
Because `..` for slices is exclusive, if you'd want a slice going from the first to the n'th element, you'd have to go &x[-1..n+1] which is hella dirty

**Comment by MovingtoMars** [comment]
@kiljacken `..` is only exclusive for the upper limit. The lower it exclusive. So you'd go `&x[0..n+1]`

**Comment by raoulvdberge** [comment]
@MovingtoMars @kiljacken indeed, pretty sure most systems work like that.

**Comment by MovingtoMars** [comment]
Question: how will you be able to create a slice from dynamic memory?

**Comment by felixangell** [comment]
@MovingtoMars How do you mean?

**Comment by MovingtoMars** [comment]
@felixangell the equivelant of
```
int *array = malloc(sizeof(int) * 20);
array[5] = 6;
```

**Comment by felixangell** [comment]
@MovingtoMars No clue, probably deserves it's own issue since this is for the syntax of an array more so than semantics + syntax

**Comment by MovingtoMars** [comment]
@felixangell In the case of arrays, syntax is tightly linked with semantics, so we need to figure it out.

**Comment by felixangell** [comment]
@MovingtoMars Well we should probably decide if we're going with the current syntax for arrays, or the proposed syntax here, then we decide?

**Comment by MovingtoMars** [comment]
So I'm thinking slices can work as references, considering they both use the `&` syntax.

Also, please `[4]int`, and `[4][8]int` etc.

**Comment by kiljacken** [comment]
I see no reason to move away from `[n]T`. Not only is the current way easier to parse, (imo) it's also more readable (`[[T; 5]; 10]` ughh).
