### ISSUE TITLE
Raw string literals

### ISSUE THREAD

**Issue by MovingtoMars** [ark-lang/rfcs#17]
Created by enclosing text in backticks. In raw string literals, escaped sequences are not parsed.

For example:
```rust
thing := `hi\n`;
thing2 := "hi\\n";
```

**Comment by kiljacken** [comment]
:+1:

**Comment by raoulvdberge** [comment]
-1, backticks suck on EU keyboards

**Comment by kiljacken** [comment]
Dude, you can disable dead keys on all major operating systems if you don't use them for accents. If you actually need the accents you can likewise setup a compose key that allows to use key combinations to re-enable these dead keys for one type.

**Comment by kiljacken** [comment]
Also, @raoulvdberge what would you propose for raw strings instead of backticks?

**Comment by raoulvdberge** [comment]
No raw strings at all? Do we really need them? Not parsing escaped sequences seems something that is not needed that much. And is typing \\ so bad?

**Comment by SamTebbs33** [comment]
It does seem a little unnecessary tbh

**Comment by kiljacken** [comment]
Raw strings unnecesary? Wow. What about regular expressions (this one matches things like `\(stuff)`):

    "\\\\\\([a-zA-Z]+\\)"

Don't we all agree that that would be way easier to reason about as:

    `\\\([a-zA-Z]+\)`

**Comment by SamTebbs33** [comment]
I didn't think of that use case.

**Comment by MovingtoMars** [comment]
It's also good for things like holding Latex, or even raw Ark/C/etc programs in a string.

**Comment by felixangell** [comment]
Well 3 of the 4 core team members are okay with this feature, so this is approved.
