### ISSUE TITLE
#trace directive

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#18]
We had the idea for directives, but the only usage that was suggested (and was the initial reason for the suggestion) was a `#link` directive. I've been playing around with OCaml, and they have a `#trace` directive. You apply this to a function, for instance a factorial:

```ocaml
let rec fact n =
match n with
      1 -> 1
    | _ -> n * fact(n - 1);;
#trace fact
```

Then when you call the function, it will trace what it does:
```
fact 5;;
fact <-- 5
fact <-- 4
fact <-- 3
fact <-- 2
fact <-- 1
fact --> 1
fact --> 2
fact --> 6
fact --> 24
fact --> 120
- : int = 120
```

This might be another handy directive for debugging, note there is also an `untrace` function which reverts this behaviour. Note the left arrow is an input, and the right arrow is a result.

Usage in Ark would probably be:

```rust
#trace fact
func fact(n: int) -> int {
    match n {
        1 => return 1;
        _ => return n * fact(n - 1);
    }
}
```

@ark-lang/owners

**Comment by kiljacken** [comment]
This would add a dependency on the standard library, which I'm not sure is
a great idea in a directive. I do agree, however, that it would be useful.
It might fit better as a macro in the standard library

**Comment by SamTebbs33** [comment]
How about implementing this as an attribute?

```
[trace]
func fact(n: int) -> int {
    match n {
        1 => return 1;
        _ => return n * fact(n - 1);
    }
}

**Comment by felixangell** [comment]
@SamTebbs33 I considered that, but having a directive means you can trace/untrace from other places in the code? Though I agree with @kiljacken that a macro may be suited best for this kind of thing.

**Comment by felixangell** [comment]
This issue was moved to ark-lang/ark#611
