### ISSUE TITLE
Implicit returns

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#19]
I think for the languages design, it would make certain examples such as my factorial example a lot cleaner if we were to allow for implicit returns. I remember reading somewhere that if you allow for implicit returns in a specific context (i.e. we only used to allow it for single line functions), then you may as well allow it everywhere else to be more consistent. Given that we already adopt a lot of things taken from functional languages, this should be another relatively important thing to adopt too given it's familiarity with function programmers and allowing for more concise and clean code.

We would still support the return statement for when you need to be explicit, but it would be encouraged to implicitly return something instead:

matching:
```rust
func fact(n: int) -> int {
    match n {
        1 => 1;
        _ => n * fact(n - 1);
    }
}
```

single line functions:
```rust
func add(a: int, b: int) -> int => a + b;
```

constructors:
```rust
func new() -> Foo {
    Foo {
        data: data,
        something: something,
    };
}
```

**Comment by MovingtoMars** [comment]
:-1: I'm against this. I like being able to look for keywords and immediately see what some code does. That's the sort of thinking that keeps the Go stdlib so readable, so even a newcomer to the language can read the source code and understand it.

**Comment by felixangell** [comment]
@MovingtoMars Fair enough. It just irritates me in some use cases, i.e. the match arms, when I have to type `return` which is longer than the thing I actually return.

**Comment by kiljacken** [comment]
I'm 50/50 on this. For more functional coffee it would be really nice, but
readability is a concern when it comes to use in more advanced functions

**Comment by raoulvdberge** [comment]
:-1: not readable enough

**Comment by vnev** [comment]
50/50 here as well. It does compromise on readability IMO.

**Comment by SamTebbs33** [comment]
How about making the match statement an expression and returning it?

```
func fact(n: int) -> int {
    return match n {
        1 => 1;
        _ => n * fact(n - 1);
    }
}
```

This could perhaps be extended to other constructs, like if-statements

**Comment by felixangell** [comment]
@SamTebbs33 
One of the plans was to make match an expression, and exhaustive. I agree that this is cleaner than how it is now. 

It seems a lot of people are mostly against implicit returns, or either on the fence about it. I think it would be nice to have since it makes code a lot more cleaner, though we are sacrificing some readability.

I think we should probably close this issue for now unless anyone has changed their mind since the creation of this issue?

@MovingtoMars 
> That's the sort of thinking that keeps the Go stdlib so readable, so even a newcomer to the language can read the source code and understand it.

I'm not sure about this. I think it's more readable because the language is very strict and enforces syntax to be written in a particular way (go fmt). I think that someone wouldn't struggle with this as long as they are familiar with the idea that returns are implicit.
Perhaps if you weren't very familiar with programming it might not make sense, but if you have a grasp of any language, it's usually quite simple to see what's going on. Given that we are adopting a reasonably complex memory model/ownership system - where you have to put a lot more thought into thinking about how memory is managed - having implicit returns is a grain of salt in terms of affecting readability/structure of code in comparison to the ownership model. 

If you take into account the "audience" of this language, which is probably more experienced developers who prefer working on the lower level, I don't think our audience would struggle reading something like this:

```rust
func fact(n: int) -> int {
    match n {
        1 => 1;
        _ => n * fact(n - 1);
    }
}
```

Though, the important part here, is that _I would like the language to be newbie friendly_, but to do this, we need to think of a way to make ownership/borrowing a lot more simpler, if not almost transparent when you write code.

P.S
Sorry for the massive wall of text, just some stuff to think about. I've finished one of the larger projects I've had to do at college so I should have a bit more free time soon. I'm slowly starting to work on Arkade more, but my PC is kind of fucked at the moment.

**Comment by 0xc6** [comment]
Consider making implicit returns optional. That is, depending on whether one wishes their codebase to be in a more functional style, they can choose whether or not to omit the keyword. I agree that they can shorten code considerably, but sometimes one does not necessarily wish to return anything; they can (as @MovingtoMars mentioned) make scanning through code more challenging, albeit only to those unpractised in the Zen of Ark. Having implicit returns may make a codebase less consistent, however, if early returns are utilised.

On a side note, something like [this](http://crystal-lang.org/2015/09/05/tools.html) adapted for Ark would be pretty useful, as it would allow one to (for example), have an overview of functions and their return types for each file. Not that one should sacrifice readability, of course, as some people may be using a plain text editor to read and/or write Ark code.

**Comment by felixangell** [comment]
This issue was moved to ark-lang/ark#610
