### ISSUE TITLE
Generics Spec

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#2]

**Comment by kiljacken** [comment]
Draft suggestion for generics spec: https://gist.github.com/kiljacken/55f7c4e429bb16c1f5bf

**Comment by raoulvdberge** [comment]
I like it :+1:

**Comment by felixangell** [comment]
@kiljacken :+1:

**Comment by raoulvdberge** [comment]
I suppose this spec is decided?

**Comment by felixangell** [comment]
I'd imagine so, I remember @MovingtoMars liked it when it was linked in the gitter.
