### ISSUE TITLE
Discarding values

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#20]
The `_` would be used for discarding values, similar to Rust/Go/OCaml. The current usage of an underscore is the following:

```rust
match x {
    _ => ...; // exhaustive, matches anything not already in the arms
}
```

Would be nice to allow this in other places too:
```
for _ in (some range when we support ranges) {
    // only iterate (range) amount of times, discard
   // the index
}
```

Also in de-structuring (I think this is already supported?), when you discard something you use an underscore:

```
match foo {
    bar(_) => ...;
}
```

A few of these examples we've already planned, however we should get a solid idea of _where_ values can be discarded.

**Comment by MovingtoMars** [comment]
This is under #5

**Comment by felixangell** [comment]
Yeah, but I don't think it covered discarding the index for a for loop though, just de-structuring stuff from tagged unions and the `_` case.

**Comment by MovingtoMars** [comment]
Well then :+1:

**Comment by kiljacken** [comment]
LGTM :+1:

**Comment by raoulvdberge** [comment]
:+1:

**Comment by felixangell** [comment]
This issue was moved to ark-lang/ark#609
