### ISSUE TITLE
Static and Dynamic Traits

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#4]
## Brief Introduction to Traits

```rust
type Bar struct {
    name: str;
}

type Baz struct {
    name: str;
}

type Foo trait {
    func fooBar();
}

impl Foo for Bar {
    func fooBar() {
        println("foobar method in foo for bar %s!", name);
    }
}

impl Foo for Baz {
    func fooBar() {
        println("foobar method in foo for baz %s!", name);
    }
}
```

## TODO
* formal spec of traits and how they work, in reasonable detail;
* how static traits work;
* how dynamic traits work;
* limitations of traits, i.e. what they can't do, and what they shouldn't do;

## Final Spec:
Update below here to account for final specs and what not

**Comment by felixangell** [comment]
@MovingtoMars Shall we close this because of interfaces?

**Comment by MovingtoMars** [comment]
yep
